### ISSUE TITLE
Theme names should not be case-sensitive

### ISSUE THREAD

**Issue by dbkaplun** [jsonresume/theme-manager#13]

**Comment by poleveD** [comment]
@secrettriangle if you are referring to the theme name in the URL, I have created a pull request with a fix for the same.

**Comment by mchelen** [comment]
For reference, uppercase is not allowed in NPM package names https://github.com/npm/npm-www/pull/410#issuecomment-27717029

**Comment by poleveD** [comment]
@mchelen yes, that is correct. We cannot have those using jsonresume to provide the theme names in small case letters, simply because they do not or need not care where the server is running or what/how it shows the ouput.

Thoughts?

**Comment by thomasdavis** [comment]
If NPM dose not allow uppercase published theme names, then this will never been an issue for us.
