### ISSUE TITLE
themes.jsonresume.org is down!

### ISSUE THREAD

**Issue by adius** [jsonresume/theme-manager#19]

**Comment by thomasdavis** [comment]
`Cannot GET /` is to be expected but otherwise the themes seem to be running -> http://themes.jsonresume.org/theme/elegant

**Comment by adius** [comment]
Aha. Then you shouldn't link it in readme.md. (…and clarify that there is no index of all themes on the root domain as most people might expect)

**Comment by PeterDaveHello** [comment]
I think we can close this now?

**Comment by thomasdavis** [comment]
yes
