### ISSUE TITLE
How do I publish themes?

### ISSUE THREAD

**Issue by aadesh** [jsonresume/theme-manager#22]
I've created a customized theme for my json resume. How do I publish it so that everyone can use it?

**Comment by mudassir0909** [comment]
Publish your package on npm using
```
npm publish
```

Make sure the package name is of the format `jsonresume-theme-yourthemename`

Examples: https://github.com/jsonresume/jsonresume-theme-modern, https://github.com/mudassir0909/jsonresume-theme-elegant
