### ISSUE TITLE
themes.jsonresume.org is down. 

### ISSUE THREAD

**Issue by codeocelot** [jsonresume/theme-manager#25]
Related: resume-cli issue 167:  https://github.com/jsonresume/resume-cli/issues/167

Last commit was 6 months ago... so I presume the host environment broke?

**Comment by thomasdavis** [comment]
Thanks for the report, checking it out now.

**Comment by PeterDaveHello** [comment]
Issue confirmed. @thomasdavis how can I help?

**Comment by dbkaplun** [comment]
Looks like it's back up. Closing.

**Comment by PeterDaveHello** [comment]
Any detail about the downtime?

**Comment by thomasdavis** [comment]
Was a server crash. It uses pm2 to automatically restart but it just didn't seem to auto restart this time.
