### ISSUE TITLE
Online Theme Editor

### ISSUE THREAD

**Issue by pomy** [jsonresume/theme-manager#34]
Hi there. Theme editor is not working properly here. Can see and change themes.  
![theme-editor](https://cloud.githubusercontent.com/assets/622421/21652185/83a87e86-d2cd-11e6-8a55-904edbbc56f4.png)

**Comment by thomasdavis** [comment]
On it now.

**Comment by thomasdavis** [comment]
Fixed it up, thanks for the report.
