### ISSUE TITLE
Cannot find packages

### ISSUE THREAD

**Issue by mudassir0909** [jsonresume/theme-manager#36]
http://registry.jsonresume.org/mudassirali

This works on my local, started to happen after my recent theme publish. Any ideas for why this could be happening?

**Comment by thomasdavis** [comment]
Node server is set to 7+

I've noticed some problems with this

**Comment by mudassir0909** [comment]
Ah I see, I'll install 7+ & fix it, thanks!

**Comment by thomasdavis** [comment]
I'm having trouble with the pug library but can't seem to figure it out.

**Comment by thomasdavis** [comment]
@mudassir0909 I installed pug-lexer explicitly and it works. So you should just be able to add it to package.json and it will work.

**Comment by mudassir0909** [comment]
> I installed pug-lexer explicitly and it works.

Thanks :)

> So you should just be able to add it to package.json and it will work.

I did publish the theme by adding `pug-lexer` previously which didn't help.

I actually `npm unpublish`ed that version 😛 I'll do some testing by upgrading my local node to 7+ & see what I can find.

**Comment by mudassir0909** [comment]
I think the error caused due to the absence of [package-lock.json](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/package-lock.json), since there was no `package-lock.json` in previous versions of node
