### ISSUE TITLE
Theme Endpoint Broken

### ISSUE THREAD

**Issue by cukejianya** [jsonresume/theme-manager#47]
I tried to run `resume serve` and received an error stating that `There was an error downloading your generated html resume from our server: Error: Unsuccessful HTTP response`

I also tried to go to https://themes.jsonresume.org/theme/ and it wouldn't load.

**Comment by eridal** [comment]
Just came here to report that themes.jsonresume.org is down, but seems like this already known :)

**Comment by thomasdavis** [comment]
Working on new serverless theme renderer here -> http://us-central1-jsonresume-58a79.cloudfunctions.net/theme/paper

**Comment by thomasdavis** [comment]
https://github.com/jsonresume/registry-server/issues/105

https://themes.jsonresume.org/kendall
